services:
  app:
    image: zcout-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8000"
    depends_on:
      - pgsql
      - soketi
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pgsql:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgsql_data_prod:/var/lib/postgresql/data

  soketi:
    image: quay.io/soketi/soketi:latest-16-alpine
    restart: unless-stopped
    environment:
      SOKETI_DEBUG: "0"
      SOKETI_DEFAULT_APP_ID: "zcout"
      SOKETI_DEFAULT_APP_KEY: "zcout-key"
      SOKETI_DEFAULT_APP_SECRET: "zcout-secret"
    ports:
      - "127.0.0.1:6001:6001"

volumes:
  pgsql_data_prod:
