<?php

return [
    'pace' => 'Explosiveness and top-speed threat over distance.',
    'acceleration' => 'How quickly the player reaches top speed from the first steps.',
    'ball_control' => 'Quality of first touch and control under pressure.',
    'dribbling' => 'Ability to beat opponents and carry the ball in tight spaces.',
    'finishing' => 'Quality and consistency of converting chances into goals.',
    'long_shots' => 'Threat and technique when shooting from outside the box.',
    'attacking_movement' => 'Timing and intelligence of runs in attacking situations.',
    'heading' => 'Effectiveness in aerial attacking and defensive duels.',
    'passing' => 'Reliability and quality of distributing the ball to teammates.',
    'crossing' => 'Accuracy and danger of deliveries from wide areas.',
    'creativity' => 'Vision and ability to create chances others do not see.',
    'leadership' => 'Presence, authority and ability to raise the level of others.',
    'concentration' => 'Consistency of focus and decision quality over time.',
    'aggression' => 'Competitive edge, intensity and willingness to engage physically.',
    'composure' => 'Calmness and control in high-pressure moments.',
    'work_rate' => 'Willingness to keep working, pressing and contributing off the ball.',
    'strength' => 'Physical power in duels, shielding and contact situations.',
    'agility' => 'Sharpness and balance when turning or changing direction.',
    'stamina' => 'Capacity to sustain intensity over the full match.',
    'marking' => 'Ability to track and stay connected to opponents defensively.',
    'tackling' => 'Timing and execution of taking the ball away cleanly.',
    'interceptions' => 'Reading passing lanes and cutting out opposition moves.',
    'penalties' => 'Quality and composure from the penalty spot.',
    'free_kicks' => 'Technique and threat from direct set pieces.',
    'gk_reflexes' => 'Shot-stopping reactions in fast close-range situations.',
    'gk_one_on_ones' => 'Ability to handle direct duels with an attacker.',
    'gk_handling' => 'Security and cleanliness when catching or controlling the ball.',
    'gk_command_of_area' => 'Authority and effectiveness dealing with crosses and crowded box situations.',
    'gk_kicking' => 'Quality of goalkeeper distribution with the feet.',
    'gk_throwing' => 'Accuracy and usefulness of goalkeeper throws to start attacks.',
    'gk_rushing_out' => 'Judgement and effectiveness when leaving the line aggressively.',
    'gk_eccentricity' => 'Tendency to play unusually adventurous or unconventional actions.',
];
