<?php

return [
    'weights' => [
        'high' => 1.5,
        'medium' => 1.00,
        'low' => 0.5,
    ],

    'position_to_archetype' => [
        'GK' => 'GK',
        'RB' => 'FULL_BACK',
        'LB' => 'FULL_BACK',
        'CB' => 'CB',
        'DM' => 'DM',
        'CM' => 'CM',
        'AM' => 'AM',
        'RM' => 'WINGER',
        'LM' => 'WINGER',
        'RW' => 'WINGER',
        'LW' => 'WINGER',
        'ST' => 'ST',
        'DEF' => 'CB',
        'MID' => 'CM',
        'ATT' => 'ST',
    ],

    'archetype_axis_weights' => [
        'ST' => [
            'ATTACK' => 'high',
            'PACE' => 'high',
            'TECHNIQUE' => 'high',
            'MENTALITY' => 'medium',
            'AERIAL' => 'medium',
            'PHYSICALITY' => 'medium',
            'PASSING' => 'low',
            'DEFENCE' => 'low',
        ],
        'WINGER' => [
            'PACE' => 'high',
            'TECHNIQUE' => 'high',
            'ATTACK' => 'high',
            'PASSING' => 'medium',
            'MENTALITY' => 'medium',
            'PHYSICALITY' => 'medium',
            'DEFENCE' => 'low',
            'AERIAL' => 'low',
        ],
        'AM' => [
            'ATTACK' => 'high',
            'TECHNIQUE' => 'high',
            'PASSING' => 'high',
            'MENTALITY' => 'medium',
            'PACE' => 'medium',
            'PHYSICALITY' => 'medium',
            'DEFENCE' => 'low',
            'AERIAL' => 'low',
        ],
        'CM' => [
            'PASSING' => 'high',
            'TECHNIQUE' => 'high',
            'MENTALITY' => 'high',
            'PHYSICALITY' => 'medium',
            'DEFENCE' => 'medium',
            'ATTACK' => 'medium',
            'PACE' => 'low',
            'AERIAL' => 'low',
        ],
        'DM' => [
            'DEFENCE' => 'high',
            'MENTALITY' => 'high',
            'PASSING' => 'high',
            'PHYSICALITY' => 'medium',
            'TECHNIQUE' => 'medium',
            'AERIAL' => 'medium',
            'PACE' => 'low',
            'ATTACK' => 'low',
        ],
        'FULL_BACK' => [
            'DEFENCE' => 'high',
            'PACE' => 'high',
            'PHYSICALITY' => 'high',
            'PASSING' => 'medium',
            'TECHNIQUE' => 'medium',
            'MENTALITY' => 'medium',
            'ATTACK' => 'low',
            'AERIAL' => 'low',
        ],
        'CB' => [
            'DEFENCE' => 'high',
            'PHYSICALITY' => 'high',
            'AERIAL' => 'high',
            'MENTALITY' => 'medium',
            'PACE' => 'medium',
            'PASSING' => 'medium',
            'TECHNIQUE' => 'low',
            'ATTACK' => 'low',
        ],
        'GK' => [
            'SHOT_STOPPING' => 'high',
            'AERIAL' => 'high',
            'RUSHING_OUT' => 'high',
            'DISTRIBUTION' => 'medium',
            'MENTALITY' => 'medium',
            'PHYSICALITY' => 'medium',
            'PACE' => 'low',
            'ECCENTRICITY' => 'low',
        ],
    ],
];
