<?php

return [
    'position_relevance' => [
        'GK' => [
            'gk_reflexes' => 100,
            'gk_one_on_ones' => 100,
            'gk_handling' => 100,
            'gk_command_of_area' => 95,
            'gk_passing' => 80,
            'gk_throwing' => 80,
            'gk_rushing_out' => 75,
            'gk_eccentricity' => 40,
            'concentration' => 70,
            'composure' => 65,
            'leadership' => 55,
            'strength' => 50,
            'agility' => 60,
            'pace' => 25,
            'acceleration' => 20,
        ],
        'CB' => [
            'marking' => 100,
            'tackling' => 100,
            'interceptions' => 100,
            'heading' => 90,
            'strength' => 85,
            'concentration' => 70,
            'composure' => 65,
            'passing' => 55,
            'pace' => 45,
            'acceleration' => 35,
        ],
        'LB' => [
            'pace' => 90,
            'acceleration' => 90,
            'crossing' => 85,
            'passing' => 70,
            'ball_control' => 65,
            'dribbling' => 60,
            'marking' => 75,
            'tackling' => 80,
            'interceptions' => 70,
            'stamina' => 85,
            'agility' => 60,
        ],
        'RB' => [
            'pace' => 90,
            'acceleration' => 90,
            'crossing' => 85,
            'passing' => 70,
            'ball_control' => 65,
            'dribbling' => 60,
            'marking' => 75,
            'tackling' => 80,
            'interceptions' => 70,
            'stamina' => 85,
            'agility' => 60,
        ],
        'DM' => [
            'marking' => 85,
            'tackling' => 90,
            'interceptions' => 95,
            'passing' => 85,
            'creativity' => 55,
            'ball_control' => 65,
            'concentration' => 75,
            'composure' => 70,
            'strength' => 65,
            'stamina' => 75,
        ],
        'CM' => [
            'passing' => 95,
            'creativity' => 90,
            'ball_control' => 80,
            'dribbling' => 65,
            'concentration' => 65,
            'composure' => 75,
            'work_rate' => 75,
            'stamina' => 70,
            'long_shots' => 60,
            'agility' => 55,
        ],
        'AM' => [
            'passing' => 85,
            'creativity' => 100,
            'ball_control' => 90,
            'dribbling' => 85,
            'finishing' => 65,
            'long_shots' => 70,
            'attacking_movement' => 75,
            'composure' => 70,
            'agility' => 60,
        ],
        'LW' => [
            'pace' => 90,
            'acceleration' => 95,
            'ball_control' => 85,
            'dribbling' => 100,
            'crossing' => 70,
            'finishing' => 65,
            'attacking_movement' => 75,
            'agility' => 75,
        ],
        'RW' => [
            'pace' => 90,
            'acceleration' => 95,
            'ball_control' => 85,
            'dribbling' => 100,
            'crossing' => 70,
            'finishing' => 65,
            'attacking_movement' => 75,
            'agility' => 75,
        ],
        'ST' => [
            'finishing' => 100,
            'attacking_movement' => 90,
            'heading' => 70,
            'ball_control' => 70,
            'dribbling' => 55,
            'pace' => 70,
            'acceleration' => 75,
            'strength' => 70,
            'composure' => 80,
            'long_shots' => 60,
        ],
    ],
    'default_relevance' => 10,
];
